# Generated by Django 2.0.7 on 2018-07-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
                ('value', models.DecimalField(decimal_places=10, max_digits=16)),
                ('price_type', models.CharField(choices=[('a', 'ask'), ('b', 'bid')], default='a', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
                ('value', models.DecimalField(decimal_places=10, max_digits=16)),
                ('price_type', models.CharField(choices=[('a', 'ask'), ('b', 'bid')], default='a', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(max_length=1000)),
                ('api_url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.Exchange'),
        ),
        migrations.AddField(
            model_name='ask',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.Exchange'),
        ),
    ]
