# Generated by Django 2.0.7 on 2018-07-08 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='datetime requested')),
                ('values', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='ask',
            name='timestamp',
            field=models.DateTimeField(verbose_name='datetime requested'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(verbose_name='datetime requested'),
        ),
        migrations.AddField(
            model_name='ask',
            name='api_request',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exchanges.ApiRequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='api_request',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exchanges.ApiRequest'),
            preserve_default=False,
        ),
    ]
