# Generated by Django 2.0.7 on 2018-07-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_auto_20180708_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='api_request',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='api_request',
        ),
    ]
