# Generated by Django 2.0.7 on 2018-07-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_auto_20180708_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='api_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchanges.ApiRequest'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='api_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchanges.ApiRequest'),
        ),
    ]
