# Generated by Django 2.0.7 on 2018-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0006_auto_20180708_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=17),
        ),
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=17),
        ),
    ]
