# Generated by Django 2.0.7 on 2018-07-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0009_auto_20180709_1015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ask',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
    ]
