# Generated by Django 2.0.7 on 2018-07-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0010_auto_20180709_1030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ask',
            unique_together={('timestamp', 'exchange', 'pair', 'value', 'volume')},
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('timestamp', 'exchange', 'pair', 'value', 'volume')},
        ),
    ]
